# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.15.1
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
z = np.zeros((10,10))
print('%d bytes' % (z.size * z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [16]:
z = np.arange(10,50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [19]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
z = np.random.random((3,3,3))
print(z)

[[[0.38242313 0.54957578 0.98932699]
  [0.87258446 0.09554158 0.37864568]
  [0.80986201 0.68424304 0.76710202]]

 [[0.44124345 0.33592754 0.37046275]
  [0.53453192 0.55314423 0.48653078]
  [0.90458316 0.45165862 0.66353075]]

 [[0.92627506 0.94053047 0.33772713]
  [0.91310804 0.09192053 0.25329895]
  [0.14433392 0.30275489 0.12514132]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
z = np.random.random((10,10))
zmin, zmax = z.min(), z.max()
print(zmin, zmax)

0.0010615223529673035 0.9907472702006065


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
z = np.random.random(10)
print(z)
zmean = z.mean()
print(zmean)

[0.13845097 0.26756823 0.79651552 0.36996779 0.34083717 0.48097
 0.01102836 0.93907758 0.70766915 0.39837121]
0.44504559831008683


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [33]:
z = np.ones((5,5))
z = np.pad(z, pad_width = 1, mode = 'constant', constant_values= 0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [50]:
print(np.nan)
print(np.inf)
print(0 * np.nan) #0
print(np.nan == np.nan) #true
print(np.inf > np.nan)#true
print(np.nan - np.nan) #0
print(np.nan in set([np.nan])) # true

print(0.3 == 0.1*3) #False   Ther reason is that only numbers that are powers of 2 can be represented precisely with a simple binary representation.
print(0.3 == 0.3*1)

nan
inf
nan
False
False
nan
True
False
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [51]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [65]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [61]:
z = np.arange(8)
print(z)
print(z[1::2])
print(z[::2])

[0 1 2 3 4 5 6 7]
[1 3 5 7]
[0 2 4 6]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [101]:
print(np.unravel_index(99,(6,7,8)))   ####index starting from 0, index 99 is the 100th element
y = np.arange(336).reshape((6,7,8))    #### shape starting from 1
print(y)
z = y[1,5,3]                           ###index starting from 0, [1,5,3] is the 2 the part, the 6 row, the 4 the column
print(z)

(1, 5, 3)
[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 2

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [107]:
z = np.tile(([0,1],[1,0]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [111]:
z = np.random.random((5,5))
z1 = (z - z.mean()) / (z.std())
print(z1)

z2 = (z - np.mean (z)) / (np.std (z))
print(z2)

[[-1.03839586  0.55941052  1.88542276  1.63072233  0.50538708]
 [ 0.67167715 -0.72471543  1.59803027 -0.48825332 -0.3449733 ]
 [-1.30057856 -0.17058412 -0.89630773  0.21264419 -1.28670206]
 [ 0.5134555  -1.08490335 -0.81844593 -0.9049636  -0.90070728]
 [-0.42059332 -0.6329874   0.78105714  1.86308214  0.79222218]]
[[-1.03839586  0.55941052  1.88542276  1.63072233  0.50538708]
 [ 0.67167715 -0.72471543  1.59803027 -0.48825332 -0.3449733 ]
 [-1.30057856 -0.17058412 -0.89630773  0.21264419 -1.28670206]
 [ 0.5134555  -1.08490335 -0.81844593 -0.9049636  -0.90070728]
 [-0.42059332 -0.6329874   0.78105714  1.86308214  0.79222218]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [113]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [117]:
z = np.ones((5,3)) @ np.ones((3,2))
print(z)

y = np.dot(np.ones((5,3)), np.ones((3,2)))
print(y)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [119]:
z = np.arange(11)
z[(z>3) & (z<8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [2]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))  ####????

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [21]:
Z = 4

print(2 << Z >> 2)
a = (2 * 2**4) / (2**2)
a

8


8.0

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
import numpy as np
print(np.array([np.nan]).astype(int))
print(np.array([np.nan]).astype(float))
print(np.array([np.nan]).astype(int).astype(float))

[-2147483648]
[nan]
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [38]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 7.03399459  4.389106   -6.70857902  3.01741454  2.45541964  6.31846232
  7.77380101  8.03321269 -1.43179623 -7.33060617]
[ 8.  5. -7.  4.  3.  7.  8.  9. -2. -8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [47]:
Z1 = np.random.randint(1,10,10)
Z2 = np.random.randint(1,10,10)
print(np.intersect1d(Z1,Z2))

[4 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [52]:

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)



In [53]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [61]:
np.sqrt(-1) == np.emath.sqrt(-1) 
### nan != 1j

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [66]:
print(np.datetime64('today', 'D'))
print(np.datetime64('today', 'D') + np.timedelta64(1,'D'))
print(np.datetime64('today', 'D') + np.timedelta64(-1,'D'))

2019-09-03
2019-09-04
2019-09-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [75]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [84]:
A = np.ones((3,3))*1
B = np.ones((3,3))*2

np.add(A,B, out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B, out =A)  ## element-wise

array([[-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5]])

In [85]:
A = np.ones((3,3))*1
B = np.ones((3,3))*2

np.add(A,B, out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.dot(A,B, out =A)  ## dot product

array([[-4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [93]:
z = np.random.uniform(0,10,10)

print(z - z%1)
print(z - z//1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[3. 5. 1. 1. 0. 6. 8. 9. 8. 1.]
[0.86036716 0.70145182 0.09402684 0.66261837 0.11255097 0.16460047
 0.30960152 0.93218367 0.54760462 0.51440347]
[3. 5. 1. 1. 0. 6. 8. 9. 8. 1.]
[3. 5. 1. 1. 0. 6. 8. 9. 8. 1.]
[3 5 1 1 0 6 8 9 8 1]
[3. 5. 1. 1. 0. 6. 8. 9. 8. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [99]:
z = np.tile(np.arange(5),(5,1))
z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [103]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [106]:
###Yield are used in Python generators.
###A generator function is defined like a normal function, 
##but whenever it needs to generate a value, 
###it does so with the yield keyword rather than return. 
###If the body of a def contains yield, the function automatically becomes a generator function.

## The yield statement suspends function’s execution and sends a value back to caller,
## but retains enough state to enable function to resume where it is left off.

def generator():
    for x in range(0,10):
        yield x
        
z = np.fromiter(generator(), dtype = float, count =-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [109]:
z = np.linspace(0,1,10,endpoint = False)[1:]
print(z)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [114]:
z = random.random(10)
z.sort()
print(z)

[0.002397   0.25762498 0.38360967 0.60950211 0.66559306 0.68938891
 0.79466796 0.96103916 0.97146798 0.98404807]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [121]:
#Short answer: when the argument is a numpy array, np.sum ultimately calls add.reduce to do the work. 
# The overhead of handling its argument and dispatching to add.reduce is why np.sum is slower.
z = np.arange(10)
np.add.reduce(z)


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [132]:
A = random.randint(0,2,10)
B = random.randint(0,2,10)

equl = np.allclose(A,B,rtol=1e-0, atol=1e-0)
print(equl)

equal = np.array_equal(A,B)
print(equal)

True
False


#### 43. Make an array immutable (read-only) (★★☆)

In [133]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [137]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.79308723 0.77750508 0.3661669  0.76053727 0.39798309 0.81287365
 1.16830785 0.85583756 0.94709891 0.36450753]
[0.96091584 0.66079975 0.63212559 1.08924366 1.24192037 0.35316406
 0.62004232 0.68100872 1.40948454 1.51723107]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [139]:
z = np.random.random(10)
n = z.argmax()
z[n] = 0
print(z)

[0.73049207 0.57488504 0.         0.21210037 0.57204476 0.44764612
 0.13411542 0.18496558 0.09004635 0.00359368]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [145]:

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [152]:
X = np.arange(8)
Y = X + 0.5
print(X,Y)
np.subtract.outer(X,Y)
C = 1.0/np.subtract.outer(X,Y)
C
print(np.linalg.det(C))

[0 1 2 3 4 5 6 7] [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [158]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
 
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [160]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [163]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z - v)).argmin()
print(z[index])

59


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [166]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [188]:
Z = np.random.randint(4, size=(4, 2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(X)
print(X.T)
print(X - X.T)

[[1 2 0 3]]
[[1]
 [2]
 [0]
 [3]]
[[ 0  1 -1  2]
 [-1  0 -2  1]
 [ 1  2  0  3]
 [-2 -1 -3  0]]


In [189]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.36197974 0.32337824 0.71838797 0.45442959 0.37816465
  0.41939028 0.39873713 0.67331929 0.89251451]
 [0.36197974 0.         0.09180496 1.04749346 0.81218128 0.67247266
  0.11992897 0.08986704 0.87418626 0.92646009]
 [0.32337824 0.09180496 0.         0.97705061 0.77766337 0.66851815
  0.09652592 0.07601654 0.78485699 0.83809991]
 [0.71838797 1.04749346 0.97705061 0.         0.48567696 0.74810731
  1.05528602 1.0477501  0.45844082 0.89052407]
 [0.45442959 0.81218128 0.77766337 0.48567696 0.         0.27820645
  0.8733432  0.85315312 0.74472528 1.11910108]
 [0.37816465 0.67247266 0.66851815 0.74810731 0.27820645 0.
  0.76307535 0.73677442 0.91294864 1.2232113 ]
 [0.41939028 0.11992897 0.09652592 1.05528602 0.8733432  0.76307535
  0.         0.03047245 0.83030818 0.83416436]
 [0.39873713 0.08986704 0.07601654 1.0477501  0.85315312 0.73677442
  0.03047245 0.         0.83588744 0.85391754]
 [0.67331929 0.87418626 0.78485699 0.45844082 0.74472528 0.91294864
  0.83030818 0.83588

In [190]:
# Much faster with scipy
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.46783255 0.69180002 0.31828492 0.7886861  0.07956029
  0.63754023 0.82555726 0.85746001 0.74302959]
 [0.46783255 0.         0.54650944 0.51944321 0.70471321 0.47575748
  0.59954769 0.77315328 0.61902053 0.68964063]
 [0.69180002 0.54650944 0.         0.43833218 0.1634138  0.63187426
  0.14437663 0.23795711 0.19275216 0.1689123 ]
 [0.31828492 0.51944321 0.43833218 0.         0.49603791 0.24053391
  0.3451234  0.52104669 0.62681911 0.44430195]
 [0.7886861  0.70471321 0.1634138  0.49603791 0.         0.71990939
  0.15205478 0.07627375 0.26025332 0.05793017]
 [0.07956029 0.47575748 0.63187426 0.24053391 0.71990939 0.
  0.56805168 0.75353976 0.80449784 0.67244239]
 [0.63754023 0.59954769 0.14437663 0.3451234  0.15205478 0.56805168
  0.         0.19288442 0.32756505 0.10668801]
 [0.82555726 0.77315328 0.23795711 0.52104669 0.07627375 0.75353976
  0.19288442 0.         0.32694698 0.08725857]
 [0.85746001 0.61902053 0.19275216 0.62681911 0.26025332 0.80449784
  0.32756505 0.32694

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [203]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [207]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
        6,  ,  , 7, 8\n
        ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [210]:
Z = np.arange(9).reshape(3,3)

for index, value in ndenumerate(Z):
    print(index,value)
for index in ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [221]:
X,Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X + Y*Y)
print(X)
print(Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
[[-1.  -1.  -1.  -1.  -1. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.   1.   1.   1.   1. ]]
[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


In [222]:
X,Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))

sigma, mu = 1.0, 0.0
G = np.exp(-( (X-mu)**2 / ( 2.0 * sigma**2 ) + (Y-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [224]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [231]:
X = np.random.rand(5, 10)
print(X)
print(X-X.mean(axis=1, keepdims=True))

[[0.72902607 0.04483921 0.47175668 0.82660854 0.54137834 0.1812928
  0.56992277 0.66683106 0.00282357 0.95857128]
 [0.10093087 0.50600163 0.87108148 0.76346014 0.80007174 0.03368518
  0.5806457  0.65832258 0.036229   0.09565207]
 [0.11081829 0.11274068 0.71363307 0.7553817  0.45618315 0.43821687
  0.97780054 0.23482168 0.9513918  0.96033046]
 [0.19074179 0.66768475 0.02223751 0.08103121 0.7788817  0.14555649
  0.82019173 0.5532358  0.6830502  0.82399548]
 [0.09702915 0.85180696 0.29268399 0.51470129 0.84903732 0.72861584
  0.6699178  0.04139942 0.32111295 0.01299649]]
[[ 0.22972104 -0.45446582 -0.02754835  0.32730351  0.0420733  -0.31801224
   0.07061774  0.16752603 -0.49648146  0.45926625]
 [-0.34367717  0.06139359  0.42647344  0.3188521   0.3554637  -0.41092286
   0.13603766  0.21371454 -0.40837904 -0.34895597]
 [-0.46031353 -0.45839115  0.14250124  0.18424988 -0.11494867 -0.13291495
   0.40666871 -0.33631014  0.38025998  0.38919864]
 [-0.28591887  0.19102409 -0.45442315 -0.39562946 

#### 59. How to sort an array by the nth column? (★★☆)

In [236]:
Z = np.random.randint(0,10,(3,3))
print(Z)
Z[Z[:,1].argsort()]

[[2 5 1]
 [8 4 1]
 [5 9 5]]


array([[8, 4, 1],
       [2, 5, 1],
       [5, 9, 5]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [238]:
Z = np.random.randint(0,3,(3,10))
print((Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [249]:
Z = np.random.uniform(0,1,(2,10))
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
n = Z.flat
print(Z)
print(array(n))
print(m)

[[0.57426183 0.83607048 0.54196022 0.02707977 0.17207921 0.17429072
  0.94743919 0.26601526 0.86822658 0.83764677]
 [0.72827808 0.73551009 0.19627662 0.29772048 0.28270276 0.8327309
  0.17876108 0.07622889 0.70072446 0.66324466]]
[0.57426183 0.83607048 0.54196022 0.02707977 0.17207921 0.17429072
 0.94743919 0.26601526 0.86822658 0.83764677 0.72827808 0.73551009
 0.19627662 0.29772048 0.28270276 0.8327309  0.17876108 0.07622889
 0.70072446 0.66324466]
0.5419602181312269


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [257]:

A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)
it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [260]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [273]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),10)
print(I)
t = np.bincount(I, minlength=len(Z))
print(t)
Z += np.bincount(I)
print(Z)


## example:  I = [8 9 8 4 4 3 8 8 4 3], Index of I = 0 1 2 3 ....
## occurance of index value: 
## occurance of indext value 0 in I: 0
## occurance of indext value 1 in I: 0
## occurance of indext value 2 in I: 0
## occurance of indext value 3 in I: 2
## occurance of indext value 4 in I: 3
## occurance of indext value 5 in I: 0
## occurance of indext value 6 in I: 0
## occurance of indext value 7 in I: 0
## occurance of indext value 8 in I: 4
## occurance of indext value 9 in I: 1
## so np.bincount(I, minlength=10)   is [0 0 0 2 3 0 0 0 4 1]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[8 9 8 4 4 3 8 8 4 3]
[0 0 0 2 3 0 0 0 4 1]
[1. 1. 1. 3. 4. 1. 1. 1. 5. 2.]


In [270]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),10)
print(I)
np.add.at(Z, I, 1)  #### add 1 to Z at index in I
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 2 2 1 2 4 4 2 0 0]
[3. 2. 5. 1. 3. 2. 1. 1. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [277]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I)  ##length = length(I) + 1 (because of 0 index position)
F2 = np.bincount(I,X)
print(F)
print(F2)

## [0 2 0 2 1 0 0 0 0 1]
## [0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]: 
## index 0: not in I
## index 1: 0 and 5 in I, weight :X[0]=1, X[5]=6
## index 2: not in I
## index 3: 1 and 3 in I, weight :X[1]=2, X[3]=4
## index 4: 4 in I, weight :X[4]=5
## ...

[0 2 0 2 1 0 0 0 0 1]
[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

In [290]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [293]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[78 38 47 27]
 [53 68 73 58]
 [69 61 41 32]]
[[78 38 47 27]
 [53 68 73 58]
 [69 61 41 32]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [297]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.5137676  0.46928345 0.51988605 0.54298607 0.39603201 0.43692899
 0.54773981 0.35754991 0.49044368 0.48236571]
0    0.513768
1    0.469283
2    0.519886
3    0.542986
4    0.396032
5    0.436929
6    0.547740
7    0.357550
8    0.490444
9    0.482366
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [298]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.34489535, 2.6260327 , 1.64205003, 0.88173599, 0.56070248])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [301]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))
print(A*B.T)
print(np.dot(A,B))


[[0.39868571 0.16717635 0.17809699]
 [0.29326595 0.32331549 0.13084589]
 [0.24396898 0.31481939 0.54170477]]
[[0.74395904 0.74125049 0.74971125]
 [0.83183772 0.74742734 0.86792457]
 [1.03381229 0.90667586 1.10049315]]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [302]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [308]:
A = np.arange(9).reshape(3,3)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [311]:
A = np.arange(9).reshape(3,3)
print(A)
A[0],A[1] = A[1],A[0]
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [3 4 5]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [319]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

### NOT correct if A is not sorted
A = [1,2,3]
B = [3,2,1]
A ==B

[1 1 2 3 4 4 6]


False

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [340]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret)
    return ret[n - 1:] / n
Z = np.arange(10)
print(moving_average(Z, n=3))

[ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.]
[ 0.  1.  3.  6.  9. 12. 15. 18. 21. 24.]
[1. 2. 3. 4. 5. 6. 7. 8.]


In [336]:
a = np.arange(10)
print(a[3:])
print(a[:-3])

[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)